### ISSUE TITLE
Папка для сериалов на другом диске

### ISSUE THREAD

**Issue by AcoustickSan** [fantomnotabene/NB-series-downloader#1]
Как указать папку с сериалами если она находится на другом разделе диска? /Volumes/{path} не работает.
![2016-08-05 12 25 34](https://cloud.githubusercontent.com/assets/2283454/17428119/c49ede3c-5b07-11e6-8099-111e92e4a198.png)

**Comment by fantomnotabene** [comment]
Поиск по умолчанию происходит в домашнем каталоге текущего пользователя.
Вы можете самостоятельно поменять логику работы этого элемента.
Открываете настройки **Alfred**, идете на вкладку **workflows**, находите то самое которое мы обсуждаем, открываете *одним щелчком*, там находите *file filter "**папка сериалов**"*<img width="673" alt="2016-08-05 18 21 54" src="https://cloud.githubusercontent.com/assets/9576189/17441411/fd154b90-5b41-11e6-92c7-4bc6d5b1bf38.png">открываете двойным кликом, идете на среднюю вкладку, *"**search scope**"* и добавляете туда **/Volumes**.
<img width="633" alt="2016-08-05 18 19 45" src="https://cloud.githubusercontent.com/assets/9576189/17441475/4ba93280-5b42-11e6-8fbd-b39d7b7f1117.png">
Сохраняете и пользуетесь. 
В следующее обновление добавлю.

**Comment by AcoustickSan** [comment]
Спасибо большое!
